# Generated by Django 5.0.4 on 2024-05-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(db_index=True, default='5 лет', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(db_index=True, default='Нет особенностей', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(db_index=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='set',
            field=models.CharField(db_index=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(db_index=True, default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(db_index=True, default=None, max_length=25),
        ),
    ]
